CREATE TABLE T_USER(
	ID VARCHAR2(20) NOT NULL,
	PW VARCHAR2(200) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	BIRTH VARCHAR2(8) NOT NULL,
	GENDER CHAR(1) NOT NULL,
	EMAIL VARCHAR2(100),
	PHONE VARCHAR2(13) NOT NULL,
	AUTHKEY CHAR(1) NOT NULL,
	AUTHSTATUS CHAR(1) NOT NULL
);

ALTER TABLE T_USER ADD CONSTRAINT T_USER_PRIMARY PRIMARY KEY (ID);

--로그인
SELECT ID, PW, NAME, BIRTH, GENDER, EMAIL, PHONE, AUTHKEY, AUTHSTATUS
	FROM T_USER
		WHERE ID = #{id} AND PW = #{pw};
	
--아이디 중복 체크
SELECT COUNT(ID) ID FROM T_USER WHERE ID=#{id}

--회원가입
INSERT INTO T_USER
(ID, PW, NAME, BIRTH, GENDER, EMAIL, PHONE, AUTHKEY, AUTHSTATUS)
VALUES('thdgml0729', '1234', '1234', '960729', 'xx','thdgml0729@naver.com', '01094097075', '1', '1');

--아이디찾기
SELECT ID FROM T_USER WHERE NAME = #{name} AND PHONE = #{phone};

--비밀번호찾기
SELECT PW FROM T_USER WHERE ID = #{id};

--------------------------------------------------------------
--OTP
CREATE TABLE OTP(
	SEQ VARCHAR2(100) NOT NULL,
	ACCESSCODE VARCHAR2(1000) NOT NULL
); 

